#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -cursor_name left_ptr

# Launch Polybar
sh $HOME/.config/polybar/launch.sh

# Launch dunst
dunst &

# Set wallpaper
feh --bg-scale $HOME/.config/bspwm/bg.jpg

bspc monitor DisplayPort-1 -d 1 2 3 4 5
bspc monitor DisplayPort-2 -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
