#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -cursor_name left_ptr

# Launch Polybar
sh $HOME/.config/polybar/launch.sh

# Launch dunst
dunst &

# Launch udiskie
udiskie &

# Launch xfce4 power manager
xfce4-power-manager &

# Set wallpaper
feh --bg-scale $HOME/.config/bspwm/bg.jpg

bspc monitor DisplayPort-1 -d 1 2 3 4 5
bspc monitor DisplayPort-2 -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Application rules
bspc rule -a firefox desktop=^2 follow=on --one-shot
bspc rule -a Alacritty desktop=^6 follow=off --one-shot
bspc rule -a thunderbird desktop=^7 follow=on
bspc rule -a vesktop desktop=^8 follow=off

# Autostart
pgrep firefox || firefox&
pgrep alacritty || alacritty&
pgrep vesktop || vesktop&
pgrep thunderbird || thunderbird&
